DROP TABLE GoogleTransit.dbo.estimativa
go

DROP TABLE GoogleTransit.dbo.viagem
go

DROP TABLE GoogleTransit.dbo.itinerario_ponto
go

DROP TABLE GoogleTransit.dbo.ponto
go

DROP TABLE GoogleTransit.dbo.feriado
go

DROP TABLE GoogleTransit.dbo.contato
go

DROP TABLE GoogleTransit.dbo.pontogeografico
go

DROP TABLE GoogleTransit.dbo.itinerario
go

DROP TABLE GoogleTransit.dbo.linha
go

DROP TABLE GoogleTransit.dbo.tarifa_formapagamento
go

DROP TABLE GoogleTransit.dbo.formapagamento
go

DROP TABLE GoogleTransit.dbo.tarifa
go

DROP TABLE GoogleTransit.dbo.agencia
go
